/**
 * Source capability matrix (PLAN.md Phase 12 §12.1–12.6).
 *
 * A single source of truth describing, for every job source Job-Pilot knows
 * about, its integration MECHANISM and what that mechanism actually supports.
 *
 *   availability:
 *     "implemented"          — a verified public / self-serve mechanism, an
 *                              adapter exists (see services/sources/*.js), it is
 *                              exposed in the Add Source catalogue.
 *     "requires-partnership" — a real API exists but needs a commercial /
 *                              partner agreement or approved developer access
 *                              for job-listing retrieval. NOT implemented, NOT
 *                              in the catalogue.
 *     "not-verified"         — no mechanism whose permitted use for bulk
 *                              job-listing retrieval could be established without
 *                              scraping. NOT implemented.
 *
 * No adapter is faked. Nothing marked non-"implemented" appears as a selectable
 * integration. Scraping / browser automation / anti-bot bypass are never used.
 */

const CAP_KEYS = [
  "listingRetrieval",
  "detailRetrieval",
  "incrementalSync",
  "updateLifecycle",
  "closedSignal",
  "applyUrl",
  "originalUrl",
  "location",
  "remoteStatus",
  "salary",
  "employmentType",
  "company",
];

/** shorthand: only the true capabilities need listing. */
const caps = (...on) => Object.fromEntries(CAP_KEYS.map((k) => [k, on.includes(k)]));

export const SOURCE_CAPABILITIES = {
  internal: {
    name: "Job-Pilot (internal recruiter jobs)",
    adapter: "internal",
    type: "internal",
    mechanism: "recruiter-created Job documents surfaced in place (no copy)",
    auth: "none",
    credentialType: null,
    availability: "implemented",
    docs: "internal",
    capabilities: caps("listingRetrieval", "detailRetrieval", "incrementalSync", "updateLifecycle", "closedSignal", "originalUrl", "location", "remoteStatus", "salary", "employmentType", "company"),
  },
  greenhouse: {
    name: "Greenhouse",
    adapter: "greenhouse",
    type: "ats",
    mechanism: "Job Board API — GET boards-api.greenhouse.io/v1/boards/{token}/jobs?content=true (the API behind a company's hosted board)",
    auth: "none (published board)",
    credentialType: null,
    availability: "implemented",
    docs: "https://developers.greenhouse.io/job-board.html",
    capabilities: caps("listingRetrieval", "detailRetrieval", "updateLifecycle", "applyUrl", "originalUrl", "location", "employmentType", "company"),
  },
  lever: {
    name: "Lever",
    adapter: "lever",
    type: "ats",
    mechanism: "Postings API — GET api.lever.co/v0/postings/{site}?mode=json (renders the company's Lever-hosted board)",
    auth: "none (published board)",
    credentialType: null,
    availability: "implemented",
    docs: "https://github.com/lever/postings-api",
    capabilities: caps("listingRetrieval", "detailRetrieval", "updateLifecycle", "applyUrl", "originalUrl", "location", "remoteStatus", "salary", "employmentType", "company"),
  },
  ashby: {
    name: "Ashby",
    adapter: "ashby",
    type: "ats",
    mechanism: "Job Posting API — POST api.ashbyhq.com/posting-api/job-board/{name} (powers jobs.ashbyhq.com/{org})",
    auth: "none (published board)",
    credentialType: null,
    availability: "implemented",
    docs: "https://developers.ashbyhq.com/reference/job-posting-api",
    capabilities: caps("listingRetrieval", "detailRetrieval", "updateLifecycle", "applyUrl", "originalUrl", "location", "remoteStatus", "salary", "employmentType", "company"),
  },
  smartrecruiters: {
    name: "SmartRecruiters",
    adapter: "smartrecruiters",
    type: "ats",
    mechanism: "Posting API — GET api.smartrecruiters.com/v1/companies/{id}/postings + per-posting detail (public, unauthenticated)",
    auth: "none (public Posting API)",
    credentialType: null,
    availability: "implemented",
    docs: "https://developers.smartrecruiters.com/reference/postingapisearch",
    capabilities: caps("listingRetrieval", "detailRetrieval", "updateLifecycle", "applyUrl", "originalUrl", "location", "remoteStatus", "employmentType", "company"),
  },
  workable: {
    name: "Workable",
    adapter: "workable",
    type: "ats",
    mechanism: "SPI v3 Jobs API — GET {subdomain}.workable.com/spi/v3/jobs + per-job detail",
    auth: "Bearer — account API access token (self-serve, account owner generates)",
    credentialType: "env-var name in config.apiTokenRef",
    availability: "implemented",
    docs: "https://workable.readme.io/reference/jobs",
    capabilities: caps("listingRetrieval", "detailRetrieval", "incrementalSync", "updateLifecycle", "closedSignal", "applyUrl", "originalUrl", "location", "remoteStatus", "employmentType", "company"),
  },
  adzuna: {
    name: "Adzuna",
    adapter: "adzuna",
    type: "aggregator",
    mechanism: "Adzuna Jobs API — GET api.adzuna.com/v1/api/jobs/{country}/search (licensed aggregator API)",
    auth: "app_id + app_key (free developer registration)",
    credentialType: "env-var names in config.appIdRef / config.appKeyRef",
    availability: "implemented",
    docs: "https://developer.adzuna.com/overview",
    capabilities: caps("listingRetrieval", "applyUrl", "originalUrl", "location", "remoteStatus", "salary", "employmentType", "company"),
  },
  jsearch: {
    name: "JSearch (RapidAPI)",
    adapter: "jsearch",
    type: "aggregator",
    mechanism: "JSearch API on RapidAPI — GET jsearch.p.rapidapi.com/search (licensed aggregator)",
    auth: "X-RapidAPI-Key",
    credentialType: "env-var name in config.apiKeyRef",
    availability: "implemented",
    docs: "https://rapidapi.com/letscrape-6bRBa3QguO5/api/jsearch",
    capabilities: caps("listingRetrieval", "applyUrl", "originalUrl", "location", "remoteStatus", "salary", "employmentType", "company"),
  },
  jooble: {
    name: "Jooble",
    adapter: "jooble",
    type: "aggregator",
    mechanism: "Jooble API — POST jooble.org/api/{key} (licensed aggregator API, free key on request)",
    auth: "API key in the URL path",
    credentialType: "env-var name in config.apiKeyRef",
    availability: "implemented",
    docs: "https://jooble.org/api/about",
    capabilities: caps("listingRetrieval", "originalUrl", "location", "salary", "company"),
  },
  themuse: {
    name: "The Muse",
    adapter: "themuse",
    type: "aggregator",
    mechanism: "The Muse public Jobs API — GET www.themuse.com/api/public/jobs?page=N (page-based; results carry refs.landing_page)",
    auth: "none required; optional api_key query param raises the hourly quota (500→3600/h)",
    credentialType: "optional env-var name in config.apiKeyRef",
    availability: "implemented",
    docs: "https://www.themuse.com/developers/api/v2",
    capabilities: caps("listingRetrieval", "detailRetrieval", "updateLifecycle", "applyUrl", "originalUrl", "location", "remoteStatus", "employmentType", "company"),
  },
  usajobs: {
    name: "USAJOBS (U.S. federal government)",
    adapter: "usajobs",
    type: "feed",
    mechanism: "Official USAJOBS Search API — GET data.usajobs.gov/api/search (page-based; MatchedObjectDescriptor carries PositionURI, PositionRemuneration, ApplicationCloseDate)",
    auth: "Authorization-Key header + registered-email User-Agent (free self-serve key)",
    credentialType: "env-var names in config.apiKeyRef / config.userAgentRef",
    availability: "implemented",
    docs: "https://developer.usajobs.gov/api-reference/get-api-search",
    capabilities: caps("listingRetrieval", "detailRetrieval", "updateLifecycle", "closedSignal", "applyUrl", "originalUrl", "location", "salary", "employmentType", "company"),
  },

  jobicy: {
    name: "Jobicy",
    adapter: "jobicy",
    type: "aggregator",
    mechanism: "Jobicy public API — GET jobicy.com/api/v2/remote-jobs?count=N (no auth; remote-only listings; canonical Jobicy URL per posting)",
    auth: "none — fair-use policy permits integrations without a separate agreement (keep Jobicy as source, preserve the canonical URL, cache)",
    credentialType: null,
    availability: "implemented",
    docs: "https://jobicy.com/jobs-rss-feed",
    capabilities: caps("listingRetrieval", "detailRetrieval", "updateLifecycle", "applyUrl", "originalUrl", "location", "remoteStatus", "salary", "employmentType", "company"),
  },

  // ── Evaluated, NOT implemented — access / authorization is required ──────
  remotive: {
    name: "Remotive",
    adapter: null,
    type: "aggregator",
    mechanism: "Remotive public API — GET remotive.com/api/remote-jobs",
    auth: "none for the free tier",
    credentialType: null,
    availability: "requires-partnership",
    docs: "https://remotive.com/api/remote-jobs",
    reason: "The free API's terms prohibit commercial redistribution without a paid agreement (private API from ~$5,000/month) and cap polling at 4×/day with 24h-delayed data. Not integrated pending a commercial licence.",
  },
  remoteok: {
    name: "RemoteOK",
    adapter: null,
    type: "aggregator",
    mechanism: "RemoteOK public API — GET remoteok.com/api (JSON)",
    auth: "none",
    credentialType: null,
    availability: "not-verified",
    docs: "https://remoteok.com/api",
    reason: "No published terms permitting programmatic bulk ingestion / redistribution; usage guidance is informal. Not integrated without an explicit licence.",
  },
  weworkremotely: {
    name: "We Work Remotely",
    adapter: null,
    type: "feed",
    mechanism: "Category RSS feeds — weworkremotely.com/categories/*/jobs.rss",
    auth: "none",
    credentialType: null,
    availability: "not-verified",
    docs: "https://weworkremotely.com/",
    reason: "RSS is provided for personal feed readers; no stated licence for aggregation/redistribution. Not integrated without permission.",
  },
  arbeitnow: {
    name: "Arbeitnow",
    adapter: null,
    type: "aggregator",
    mechanism: "Arbeitnow Job Board API — GET www.arbeitnow.com/api/job-board-api (page-based, no auth)",
    auth: "none",
    credentialType: null,
    availability: "not-verified",
    docs: "https://www.arbeitnow.com/terms",
    reason:
      "Phase 27 re-review: the API is documented for external use but the Terms grant no explicit redistribution/aggregation licence, attribution is unspecified, and the licence 'automatically terminates' on any restriction breach with a requirement to 'destroy any downloaded materials' — incompatible with persisting a job catalogue. Not integrated pending explicit permission (hello@arbeitnow.com).",
  },
  himalayas: {
    name: "Himalayas",
    adapter: null,
    type: "aggregator",
    mechanism: "Himalayas public jobs API — cursor-paginated JSON, no auth (himalayas.app/docs/remote-jobs-api)",
    auth: "none",
    credentialType: null,
    availability: "not-verified",
    docs: "https://himalayas.app/docs/remote-jobs-api",
    reason:
      "Phase 27 re-review: the API is public and free, but the published usage policy explicitly says 'do not submit Himalayas jobs to third-party websites' and names aggregators (Jooble, Neuvoo, Google Jobs). Job-Pilot is a third-party aggregator, so its intended use is NOT clearly permitted. Not integrated pending written permission (hi@himalayas.app).",
  },
  ziprecruiter: {
    name: "ZipRecruiter",
    adapter: null,
    type: "job-board",
    mechanism: "ZipRecruiter Partner / Publisher API",
    auth: "approved partner credentials",
    credentialType: "partner credentials",
    availability: "requires-partnership",
    docs: "https://www.ziprecruiter.com/publishers",
    reason: "Job-search API access is limited to approved publishers/partners.",
  },
  dice: {
    name: "Dice",
    adapter: null,
    type: "job-board",
    mechanism: "Dice partner feed",
    auth: "partner agreement",
    credentialType: "partner credentials",
    availability: "requires-partnership",
    docs: "https://www.dice.com/",
    reason: "The former open Dice jobs API was retired; current access is partner-gated.",
  },
  careerbuilder: {
    name: "CareerBuilder",
    adapter: null,
    type: "job-board",
    mechanism: "CareerBuilder partner API",
    auth: "partner agreement",
    credentialType: "partner credentials",
    availability: "requires-partnership",
    docs: "https://www.careerbuilder.com/",
    reason: "Job data is available only through a partner/commercial agreement.",
  },
  monster: {
    name: "Monster",
    adapter: null,
    type: "job-board",
    mechanism: "Monster partner integrations",
    auth: "partner agreement",
    credentialType: "partner credentials",
    availability: "requires-partnership",
    docs: "https://partner.monster.com/",
    reason: "No self-serve job-listing API; partner integration only.",
  },
  simplyhired: {
    name: "SimplyHired",
    adapter: null,
    type: "job-board",
    mechanism: "No public job-listing API",
    auth: "n/a",
    credentialType: null,
    availability: "not-verified",
    docs: "https://www.simplyhired.com/",
    reason: "Owned by Indeed; no permitted bulk retrieval mechanism could be established.",
  },
  "talent.com": {
    name: "Talent.com",
    adapter: null,
    type: "aggregator",
    mechanism: "Talent.com publisher / XML feed programme",
    auth: "publisher agreement",
    credentialType: "publisher credentials",
    availability: "requires-partnership",
    docs: "https://www.talent.com/",
    reason: "Feed access requires a publisher/traffic-partner agreement.",
  },
  hirist: {
    name: "Hirist",
    adapter: null,
    type: "job-board",
    mechanism: "No official public job-listing API — only third-party scrapers exist",
    auth: "n/a",
    credentialType: null,
    availability: "not-verified",
    docs: "https://www.hirist.tech/",
    reason: "No documented public API or feed for programmatic job-listing retrieval. Third-party scraping is not a permitted mechanism.",
  },
  ycombinator: {
    name: "Y Combinator — Work at a Startup",
    adapter: null,
    type: "job-board",
    mechanism: "No official public jobs API; community projects index YC companies (not postings) via Algolia",
    auth: "n/a",
    credentialType: null,
    availability: "not-verified",
    docs: "https://www.workatastartup.com/",
    reason: "Work at a Startup exposes no official job-listing API. Company-directory mirrors do not cover individual job postings.",
  },
  freshersworld: {
    name: "Freshersworld",
    adapter: null,
    type: "job-board",
    mechanism: "No public job-listing API",
    auth: "commercial agreement",
    credentialType: null,
    availability: "requires-partnership",
    docs: "https://www.freshersworld.com/",
    reason: "Listing data is available only through a commercial/partner agreement.",
  },
  "google-jobs": {
    name: "Google Jobs",
    adapter: null,
    type: "job-board",
    mechanism: "Google for Jobs is an indexing surface fed by schema.org JobPosting structured data on publisher sites",
    auth: "n/a",
    credentialType: null,
    availability: "not-verified",
    docs: "https://developers.google.com/search/docs/appearance/structured-data/job-posting",
    reason: "Not a retrieval API — Google exposes no endpoint to read job listings; it only ranks publishers' own structured data.",
  },
  linkedin: {
    name: "LinkedIn",
    adapter: null,
    type: "job-board",
    mechanism: "LinkedIn Talent / Job Posting APIs — partner programme only",
    auth: "approved partner OAuth credentials",
    credentialType: "partner credentials",
    availability: "requires-partnership",
    docs: "https://learn.microsoft.com/linkedin/talent/",
    reason: "No public job-listing retrieval API. The Talent APIs require an approved LinkedIn partnership; public pages are not permitted for bulk retrieval.",
  },
  indeed: {
    name: "Indeed",
    adapter: null,
    type: "job-board",
    mechanism: "Indeed Publisher / Employer APIs",
    auth: "publisher account / OAuth (approval-gated)",
    credentialType: "publisher credentials",
    availability: "requires-partnership",
    docs: "https://docs.indeed.com/",
    reason: "The legacy Publisher search API was retired; current job-data access is via approval-gated employer/partner programmes.",
  },
  naukri: {
    name: "Naukri (InfoEdge)",
    adapter: null,
    type: "job-board",
    mechanism: "No public job-listing API",
    auth: "commercial agreement",
    credentialType: null,
    availability: "requires-partnership",
    docs: "https://www.naukri.com/",
    reason: "Job data is available only through a commercial data agreement with InfoEdge. No self-serve API.",
  },
  glassdoor: {
    name: "Glassdoor",
    adapter: null,
    type: "job-board",
    mechanism: "Glassdoor API — partner access only; job endpoints deprecated for general use",
    auth: "partner key",
    credentialType: "partner credentials",
    availability: "requires-partnership",
    docs: "https://www.glassdoor.com/developer/",
    reason: "The public API no longer serves job listings; job access requires a partner agreement.",
  },
  wellfound: {
    name: "Wellfound (AngelList Talent)",
    adapter: null,
    type: "job-board",
    mechanism: "No documented public job-listing API",
    auth: "n/a",
    credentialType: null,
    availability: "not-verified",
    docs: "https://wellfound.com/",
    reason: "No mechanism for permitted bulk job-listing retrieval could be established without scraping.",
  },
  instahyre: { name: "Instahyre", adapter: null, type: "job-board", mechanism: "No public API", auth: "n/a", credentialType: null, availability: "not-verified", docs: "https://www.instahyre.com/", reason: "No permitted bulk retrieval mechanism." },
  cutshort: { name: "Cutshort", adapter: null, type: "job-board", mechanism: "No public API", auth: "n/a", credentialType: null, availability: "not-verified", docs: "https://cutshort.io/", reason: "No permitted bulk retrieval mechanism." },
  foundit: { name: "Foundit (formerly Monster India)", adapter: null, type: "job-board", mechanism: "No public job-listing API", auth: "commercial agreement", credentialType: null, availability: "requires-partnership", docs: "https://www.foundit.in/", reason: "Job data requires a commercial agreement." },
  shine: { name: "Shine", adapter: null, type: "job-board", mechanism: "No public API", auth: "n/a", credentialType: null, availability: "not-verified", docs: "https://www.shine.com/", reason: "No permitted bulk retrieval mechanism." },
  timesjobs: { name: "TimesJobs", adapter: null, type: "job-board", mechanism: "No public API", auth: "n/a", credentialType: null, availability: "not-verified", docs: "https://www.timesjobs.com/", reason: "No permitted bulk retrieval mechanism." },
  internshala: { name: "Internshala", adapter: null, type: "job-board", mechanism: "No public job/internship listing API", auth: "commercial agreement", credentialType: null, availability: "requires-partnership", docs: "https://internshala.com/", reason: "Listing data requires a partner/commercial agreement." },
};

/** @returns {string[]} adapter names that are actually implemented. */
export function implementedSourceKeys() {
  return Object.values(SOURCE_CAPABILITIES)
    .filter((s) => s.availability === "implemented" && s.adapter)
    .map((s) => s.adapter);
}

/** The full matrix as an array, safe for an admin response (no secrets). */
export function capabilityMatrix() {
  return Object.entries(SOURCE_CAPABILITIES).map(([key, s]) => ({
    key,
    name: s.name,
    adapter: s.adapter,
    type: s.type,
    mechanism: s.mechanism,
    auth: s.auth,
    credentialType: s.credentialType,
    availability: s.availability,
    docs: s.docs,
    reason: s.reason || "",
    capabilities: s.capabilities || null,
  }));
}
