/**
 * Workable source adapter.
 *
 * MECHANISM (verified — Workable SPI "Server Public Integration" Jobs API):
 *   GET https://{subdomain}.workable.com/spi/v3/jobs?state=published
 *   GET https://{subdomain}.workable.com/spi/v3/jobs/{shortcode}         (per job)
 *   Header: Authorization: Bearer <account API access token>
 *
 * This is a documented, authorized, self-serve integration — the token is
 * generated by the Workable account owner (Integrations → API Access Token). No
 * scraping, no browser automation. The list omits the description, so a bounded
 * per-job detail fetch supplies it.
 * Docs: https://workable.readme.io/reference/jobs
 *
 * Config (JobSource.config — never secrets):
 *   subdomain    (required)  the Workable account subdomain
 *   apiTokenRef  (required)  ENV VAR NAME holding the Bearer token (default WORKABLE_API_TOKEN)
 *   companyName  (optional)  display fallback
 *   maxDetail    (optional)  cap on detail fetches per sync (default 120, max 300)
 *   baseUrl      (optional)  tests only
 *
 * `application_url` (Workable-hosted apply page) is preserved as applyUrl,
 * `url` as originalUrl. `applyType` = external. Salary is not in the SPI jobs
 * payload — never fabricated. The token is never logged.
 */
import { BaseSourceAdapter, registerAdapter } from "./base.js";
import { safeGet, throttleHost, SourceHttpError } from "./httpClient.js";
import { resolveEnvRefs } from "./aggregatorShared.js";
import { cleanStr, pickUrl, toDate, mapEmploymentType } from "./atsShared.js";

export const WORKABLE_ADAPTER = "workable";
const MAX_PAGES = 3;
const DEFAULT_MAX_DETAIL = 120;
const HARD_MAX_DETAIL = 300;
const SUBDOMAIN_RE = /^[a-z0-9][a-z0-9-]{0,60}$/i;

export function mapWorkableJob(job, ctx = {}) {
  if (!job || !job.shortcode) return null;
  const title = cleanStr(job.title) || cleanStr(job.full_title);
  if (!title) return null;

  const loc = job.location || {};
  const location =
    cleanStr(loc.location_str) ||
    [cleanStr(loc.city), cleanStr(loc.region), cleanStr(loc.country)].filter(Boolean).join(", ");

  return {
    externalId: String(job.shortcode),
    title,
    description: cleanStr(job.full_description) || cleanStr(job.description),
    companyName: ctx.companyName || "",
    companyDomain: "",
    location,
    country: cleanStr(loc.country),
    workType: loc.telecommuting === true ? "Remote" : "",
    jobType: mapEmploymentType(job.employment_type),
    department: cleanStr(job.department),
    tags: [cleanStr(job.department), cleanStr(job.function)].filter(Boolean),
    skills: [],
    originalUrl: pickUrl(job.url, job.shortlink, job.application_url),
    applyUrl: pickUrl(job.application_url, job.shortlink, job.url),
    postedAt: toDate(job.created_at || job.published_on),
    sourceUpdatedAt: toDate(job.updated_at),
  };
}

export class WorkableAdapter extends BaseSourceAdapter {
  constructor() {
    super({ name: WORKABLE_ADAPTER, type: "ats" });
  }

  resolve(source) {
    const cfg = source.config || {};
    const subdomain = cfg.subdomain;
    if (!subdomain || typeof subdomain !== "string" || !SUBDOMAIN_RE.test(subdomain)) {
      throw new SourceHttpError("workable: config.subdomain is required (valid account subdomain)", "config");
    }
    const { token } = resolveEnvRefs({ token: cfg.apiTokenRef || "WORKABLE_API_TOKEN" });
    if (!token) {
      throw new SourceHttpError("workable: API token not configured (set the env var named by config.apiTokenRef)", "config");
    }
    const base = String(cfg.baseUrl || `https://${subdomain}.workable.com`).replace(/\/+$/, "");
    return { base, token, subdomain };
  }

  async fetch(source) {
    const cfg = source.config || {};
    const { base, token } = this.resolve(source);
    const host = new URL(base).hostname;
    const allowedHosts = cfg.baseUrl ? undefined : [host];
    const headers = { Authorization: `Bearer ${token}` };
    const scrub = (msg) => String(msg || "").split(token).join("***");
    const maxDetail = Math.min(Number(cfg.maxDetail) || DEFAULT_MAX_DETAIL, HARD_MAX_DETAIL);
    const companyName = cfg.companyName || "";

    const summaries = [];
    let nextUrl = `${base}/spi/v3/jobs?state=published&limit=100`;
    for (let page = 0; page < MAX_PAGES && nextUrl; page += 1) {
      await throttleHost(host, source.rateLimitPerMin);
      let payload;
      try {
        const res = await safeGet(nextUrl, { timeoutMs: cfg.timeoutMs || 15000, allowedHosts, headers, userAgent: "JobPilot-JobSync/1.0 (+workable)" });
        payload = JSON.parse(res.body);
      } catch (err) {
        throw new SourceHttpError(`workable: ${scrub(err.message)}`, err.kind || "network");
      }
      if (!payload || !Array.isArray(payload.jobs)) {
        if (page === 0) throw new SourceHttpError("workable: unexpected list shape (missing jobs[])", "response");
        break;
      }
      summaries.push(...payload.jobs);
      nextUrl = payload.paging?.next && /^https:\/\//.test(payload.paging.next) ? payload.paging.next : null;
    }

    const raw = [];
    for (const summary of summaries.slice(0, maxDetail)) {
      if (!summary?.shortcode) continue;
      try {
        await throttleHost(host, source.rateLimitPerMin);
        const res = await safeGet(`${base}/spi/v3/jobs/${encodeURIComponent(summary.shortcode)}`, {
          timeoutMs: cfg.timeoutMs || 15000,
          allowedHosts,
          headers,
          userAgent: "JobPilot-JobSync/1.0 (+workable)",
        });
        const detail = JSON.parse(res.body);
        const mapped = mapWorkableJob({ ...summary, ...detail }, { companyName });
        if (mapped && mapped.description) raw.push(mapped);
      } catch {
        // skip one bad posting
      }
    }
    return raw;
  }
}

export const workableAdapter = new WorkableAdapter();
registerAdapter(workableAdapter);
