import mongoose from "mongoose";

const userSchema = new mongoose.Schema({
    fullname: {
        type: String,
        required: true,
    },
    email: {
        type: String,
        required: true,
        unique: true,
    },
    phoneNumber: {
        type: Number,
        default: 0,
    },
    password: {
        type: String,
        required: true,
    },
    roles: {
        jobSeeker: { type: Boolean, default: false },
        recruiter: { type: Boolean, default: false },
    },
    currentRole: {
        type: String,
        enum: ['jobSeeker', 'recruiter', null],
        default: null,
    },
    profileCompleted: {
        type: Boolean,
        default: false,
    },
    profileCompletionScore: {
        type: Number,
        default: 0,
        min: 0,
        max: 100,
    },
    profile: {
        bio: { type: String },
        summary: { type: String, maxlength: 1000 },
        skills: [{
            name: { type: String, required: true },
            proficiency: { type: String, enum: ['Beginner', 'Intermediate', 'Expert'], default: 'Intermediate' },
        }],
        resumes: [{
            url: { type: String, required: true },
            originalName: { type: String },
            size: { type: Number },
            uploadedAt: { type: Date, default: Date.now },
            isPrimary: { type: Boolean, default: false },
        }],
        company: { type: mongoose.Schema.Types.ObjectId, ref: 'Company' },
        profilePhoto: { type: String, default: "" },
        headline: { type: String },
        dateOfBirth: { type: Date },
        gender: { type: String },
        location: { type: String },
        github: { type: String },
        portfolio: { type: String },
        socialLinks: {
            linkedin: { type: String },
            twitter: { type: String },
            website: { type: String },
        },
        experience: [{
            title: String,
            company: String,
            location: String,
            startDate: Date,
            endDate: Date,
            isCurrent: Boolean,
            description: String,
        }],
        education: [{
            degree: String,
            institution: String,
            fieldOfStudy: String,
            startYear: Number,
            endYear: Number,
            grade: String,
        }],
        projects: [{
            title: { type: String, required: true },
            description: { type: String },
            techStack: [String],
            liveUrl: { type: String },
            repoUrl: { type: String },
            thumbnailUrl: { type: String },
        }],
        certifications: [{
            name: { type: String, required: true },
            issuingOrg: { type: String },
            issueDate: { type: Date },
            credentialUrl: { type: String },
            certificateFileUrl: { type: String },
        }],
        preferredJobRole: { type: String },
        preferredSalary: { type: String },
        employmentType: { type: String },
        workPreference: { type: String },
        companyName: { type: String },
        companyEmail: { type: String },
        companyWebsite: { type: String },
        designation: { type: String },
        companySize: { type: String },
        industry: { type: String },
        companyLogo: { type: String },
        verificationStatus: {
            type: String,
            enum: ['pending', 'verified', 'rejected'],
            default: 'pending',
        },
        noticePeriod: { type: String },
        availableFrom: { type: Date },
        willingToRelocate: { type: Boolean, default: false },
        visibility: {
            profileVisible: { type: Boolean, default: true },
            resumeVisible: { type: Boolean, default: true },
            showEmail: { type: Boolean, default: false },
            openToWork: { type: Boolean, default: false },
        },
    },
}, { timestamps: true });

export const User = mongoose.model("User", userSchema);
